language: node_js
node_js:
  - "6.9.2"
script:
  - echo "Deploying!"
install:
  - npm install -g firebase-tools webpack
after_success:
  - npm run build; firebase deploy --token $FIREBASE_TOKEN --project iron-platter
